---
require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    # These are mostly managed by Rails. Fixing violations causes it to be harder to diff them when
    # running rails app:update
    - config/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
