AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - test/**/*
