version: '3'

volumes:
  postgres_data:

services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: development
    image: samkillgallon/board-games
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack_dev_server
      DATABASE_HOST: postgres
      DATABASE_USERNAME: ${DATABASE_USERNAME}
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
    depends_on:
      - postgres
      - webpack_dev_server

  postgres:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached

  webpack_dev_server:
    command: ./bin/webpack-dev-server
    build:
      context: .
      args:
        RAILS_ENV: development
    image: samkillgallon/board-games
    environment:
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
